- First digit must be the max number from position 0 to k-1, where k is length of bank, as units of 10 will always be higher than units of 1
- Instead of going through the whole thing, finding max digit, then finding the max digit AFTER that digit, we should be able to iterate through one at a time 
- Set joltages to 0,0
- Consider position x. 
    - If position x is higher than max first digit, set x as max first digit and set x+1 as max second digit
    - Else if higher than max second digit, set as max second digit
- Must go from 0 - k -1

## Part 1

In [ ]:

import numpy as np

with open('3-input.txt', 'r') as f:
    banks = np.array([np.array([int(d) for d in line.strip()]) for line in f])

joltages = []
for b in banks:
    print(f"Bank: {b}")

    # Right-to-left single pass 
    best_ones = -1             # max digit to the right of current position
    best_tens = 0              # tens digit of the best pair found
    best_ones_digit = 0        # ones digit of the best pair found

    # Scan from rightmost to leftmost
    for i in range(b.shape[0] - 1, -1, -1):
        x = b[i]

        # If there exists a digit to the right, consider the pair (x, best_ones)
        if best_ones >= 0:
            # Compare: (x, best_ones) vs (best_tens, best_ones_digit)
            if (x > best_tens) or (x == best_tens and best_ones > best_ones_digit):
                best_tens = x
                best_ones_digit = best_ones

        # Update the max "ones to the right"
        if x > best_ones:
            best_ones = x

    joltage = np.array([best_tens, best_ones_digit], dtype=int)
    print(f"Joltage: {joltage[0]}{joltage[1]}")
    joltages.append(joltage)

joltages = np.array(joltages)
numbers = joltages[:, 0] * 10 + joltages[:, 1]
total_output_joltage = np.sum(numbers)
print(f"Total Output Joltage: {total_output_joltage}")


Bank: [5 3 1 3 3 1 3 2 2 2 1 3 3 2 2 3 2 3 2 2 2 2 1 7 3 2 2 2 2 2 1 3 2 2 2 3 2
 2 4 3 5 2 2 2 2 2 4 3 2 4 2 2 2 2 3 2 2 3 2 3 2 2 2 2 3 2 2 3 2 2 3 3 2 1
 2 2 5 2 5 3 2 2 1 3 2 2 3 2 3 2 5 5 2 3 2 4 3 2 5 3]
Joltage: 75
Bank: [4 6 4 3 4 3 4 4 3 5 4 9 8 5 5 7 2 3 5 5 3 4 3 6 5 2 4 3 2 4 4 5 4 2 5 7 4
 3 2 3 5 5 3 4 4 3 4 2 5 4 5 5 3 7 3 3 9 4 3 4 7 5 2 4 4 1 7 5 4 5 6 5 6 5
 5 4 2 5 4 3 2 3 4 7 7 6 4 6 3 6 2 5 6 5 3 3 2 3 9 3]
Joltage: 99
Bank: [4 3 6 8 3 5 5 3 3 4 4 5 5 4 4 4 3 2 4 4 4 6 4 4 3 3 4 4 9 6 4 4 4 5 4 3 6
 4 4 4 4 4 4 5 3 5 5 4 3 5 6 4 9 7 4 4 4 9 4 5 5 8 3 5 1 3 4 4 6 5 3 4 4 4
 4 6 4 5 7 4 4 2 4 3 1 4 4 4 9 4 9 5 4 6 8 3 7 5 5 4]
Joltage: 99
Bank: [1 2 3 3 2 2 2 4 6 2 8 4 2 2 6 4 8 3 6 2 2 2 3 2 3 3 4 3 4 3 8 1 3 3 2 4 1
 4 4 1 4 3 3 3 4 2 5 2 3 5 2 2 5 2 3 4 3 3 2 3 3 4 3 3 1 7 2 5 2 3 2 1 2 1
 2 4 4 7 2 1 2 9 3 2 3 3 4 3 3 4 3 2 6 2 4 5 2 6 5 4]
Joltage: 96
Bank: [2 3 6 2 5 2 2 1 3 4 2 2 4 3 2 1 2 3 2 8 2 1 1 5 1 3 5 7 2 3 2 1 2 5 2 2 6
 8 1 6 1 5 6 2 2 5 2 8 2 2 2 8 

In [22]:
joltages

array([[7, 5, 5, ..., 2, 5, 3],
       [9, 9, 7, ..., 6, 9, 3],
       [9, 9, 9, ..., 5, 5, 4],
       ...,
       [9, 9, 9, ..., 3, 4, 3],
       [5, 5, 5, ..., 4, 3, 4],
       [9, 9, 6, ..., 9, 4, 3]], shape=(200, 12))

In [21]:
numbers

array([75, 99, 99, 96, 88, 94, 55, 98, 98, 99, 77, 99, 76, 77, 88, 99, 99,
       89, 98, 77, 99, 98, 76, 75, 64, 77, 75, 88, 99, 66, 99, 88, 99, 65,
       75, 85, 88, 98, 98, 85, 99, 99, 97, 87, 55, 87, 88, 88, 94, 98, 63,
       88, 88, 97, 99, 96, 66, 77, 87, 65, 77, 77, 88, 99, 77, 98, 88, 87,
       88, 99, 55, 88, 75, 88, 77, 97, 99, 63, 98, 77, 88, 66, 86, 98, 99,
       89, 99, 99, 86, 88, 88, 88, 98, 99, 86, 64, 55, 89, 99, 99, 55, 98,
       99, 98, 99, 88, 88, 66, 99, 99, 99, 87, 99, 88, 99, 66, 77, 98, 94,
       98, 43, 98, 87, 98, 87, 87, 66, 77, 86, 88, 66, 75, 99, 99, 95, 94,
       97, 64, 99, 99, 99, 66, 88, 99, 88, 99, 86, 87, 99, 98, 86, 99, 55,
       98, 98, 75, 88, 88, 89, 97, 97, 98, 66, 99, 77, 76, 97, 96, 99, 86,
       92, 76, 77, 88, 99, 89, 99, 97, 88, 98, 86, 66, 78, 99, 99, 66, 66,
       96, 66, 86, 99, 99, 88, 99, 81, 55, 99, 99, 55, 99], dtype=object)

## Part 2

In [23]:
def max_lex_subsequence_stack(A):
    drops = len(A) - 12
    stack = []
    for x in A:
        while stack and drops > 0 and stack[-1] < x:
            stack.pop()
            drops -= 1
        stack.append(x)
    return stack[:12]

joltages = np.array([max_lex_subsequence_stack(bank) for bank in banks])
weights = np.array([10**p for p in range(11, -1, -1)], dtype=object)
row_numbers = (joltages.astype(object) * weights).sum(axis=1)
sum(row_numbers)

172740584266849

In [20]:
joltages


array([[7, 5, 5, ..., 2, 5, 3],
       [9, 9, 7, ..., 6, 9, 3],
       [9, 9, 9, ..., 5, 5, 4],
       ...,
       [9, 9, 9, ..., 3, 4, 3],
       [5, 5, 5, ..., 4, 3, 4],
       [9, 9, 6, ..., 9, 4, 3]], shape=(200, 12))